### ISSUE TITLE
Doesn't work with Gatsby 2.9.0

### ISSUE THREAD

**Issue by trickydisco78** [birkir/gatsby-source-prismic-graphql#43]
Just upgraded Gatsby to 2.9.0 and get the following error

error Plugin gatsby-source-prismic-graphql returned an error

  TypeError: createPageDependency is not a function
  
  - gatsby-node.js:100 NamespaceUnderFieldTransform.resolver
    [greatstate]/[gatsby-source-graphql]/gatsby-node.js:100:7

**Comment by eknowles** [comment]
according to the gatsby changelog they added this method back in 2.9.2
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#292-2019-06-12

try upgrading gatsby to that specific version and try again?

**Comment by birkir** [comment]
Thanks for the insight @eknowles 

This plugin does not work with gatsby version `2.9.0 - 2.9.1`
